//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vampsdemo.Models.Data_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public int role_master_id { get; set; }
        public int user_id { get; set; }
        public bool active { get; set; }
    
        public virtual role_master role_master { get; set; }
        public virtual user_details user_details { get; set; }
    }
}
